using Examination_System.Models;

namespace Examination_System.DTOS
{
    public class ExamDTO
    {
        public string? Title { get; set; }
        public string? Description { get; set; }
        public ExamType Type { get; set; }
        public DateTime? AvailableFrom { get; set; }
        public DateTime? AvailableTo { get; set; }
        public int DurationInMinutes { get; set; }
        public bool IsAutoGenerated { get; set; }
        public List<QuestionDTO>? Questions { get; set; }
    }
}
