using Examination_System.Models;

namespace Examination_System.ViewModels
{
    public class CreateExamWithQuestionsVM
    {
        public string Title { get; set; }
        public string? Description { get; set; }
        public ExamType Type { get; set; }
        public DateTime? AvailableFrom { get; set; }
        public DateTime? AvailableTo { get; set; }
        public int DurationInMinutes { get; set; }
        public bool IsAutoGenerated { get; set; }
        public int NumberOfQuestions { get; set; } 
        public int CourseId { get; set; }
        public int InstructorId { get; set; }

        public List<int>? SelectedQuestionIds { get; set; }
    }
}
