using Examination_System.Models;
using System.ComponentModel.DataAnnotations;

namespace Examination_System.ViewModels
{
    public class UpdateExamVM
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string? Title { get; set; }
        [Required()]
        public string? Description { get; set; }
        [Required()]
        public ExamType Type { get; set; }
        [Required()]
        public DateTime? AvailableFrom { get; set; }
        [Required()]
        public DateTime? AvailableTo { get; set; }
        [Required()]
        public int DurationInMinutes { get; set; }
        [Required()]
        public bool IsAutoGenerated { get; set; }
        [Required()]
        public int CourseId { get; set; }
        [Required()]
        public int InstructorId { get; set; }
    }
}
