using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Models
{
    public class Exam : BaseEntity
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public ExamType Type { get; set; }
        public DateTime? AvailableFrom { get; set; }
        public DateTime? AvailableTo { get; set; }
        public int DurationInMinutes { get; set; }
        public bool IsAutoGenerated { get; set; }
        public int? TotalQuestions { get; set; }
        [ForeignKey(nameof(Course))]    
        public int CourseId { get; set; }
        public Course? Course { get; set; }
        public int InstructorId { get; set; }

        [ForeignKey(nameof(Instructor))]
        public Instructor? Instructor { get; set; }
        public ICollection<ExamQuestion>? ExamQuestions { get; set; }
        public ICollection<ExamAssignment>? ExamAssignments { get; set; }
        public ICollection<ExamAttempt>? ExamAttempts { get; set; }
    }

    public enum ExamType
    {
        Quiz,
        Final
    }
}
